bias_frames:
  files:
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Bias/Bias_1.0ms_Bin1_20241125-001808_0001.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Bias/Bias_1.0ms_Bin1_20241125-001813_0002.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Bias/Bias_1.0ms_Bin1_20241125-001817_0003.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Bias/Bias_1.0ms_Bin1_20241125-001821_0004.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Bias/Bias_1.0ms_Bin1_20241125-001826_0005.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Bias/Bias_1.0ms_Bin1_20241125-001830_0006.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Bias/Bias_1.0ms_Bin1_20241125-001834_0007.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Bias/Bias_1.0ms_Bin1_20241125-001838_0008.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Bias/Bias_1.0ms_Bin1_20241125-001843_0009.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Bias/Bias_1.0ms_Bin1_20241125-001847_0010.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Bias/Bias_1.0ms_Bin1_20241125-001851_0011.fit
  method: winsorized-mean
dark_frames:
  files:
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Dark/Dark_300.0s_Bin1_20241124-232737_0001.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Dark/Dark_300.0s_Bin1_20241124-233239_0002.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Dark/Dark_300.0s_Bin1_20241124-233742_0003.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Dark/Dark_300.0s_Bin1_20241124-234245_0004.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Dark/Dark_300.0s_Bin1_20241124-234747_0005.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Dark/Dark_300.0s_Bin1_20241124-235250_0006.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Dark/Dark_300.0s_Bin1_20241124-235753_0007.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Dark/Dark_300.0s_Bin1_20241125-000256_0008.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Dark/Dark_300.0s_Bin1_20241125-000759_0009.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Dark/Dark_300.0s_Bin1_20241125-001301_0010.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Dark/Dark_300.0s_Bin1_20241125-001804_0011.fit
  method: winsorized-mean
darkflat_frames:
  files: []
  method: winsorized-mean
flat_frames:
  files:
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Flat/Flat_15.0s_Bin1_5_20241123-053345_0001.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Flat/Flat_15.0s_Bin1_5_20241123-053403_0002.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Flat/Flat_15.0s_Bin1_5_20241123-053421_0003.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Flat/Flat_15.0s_Bin1_5_20241123-053439_0004.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Flat/Flat_15.0s_Bin1_5_20241123-053456_0005.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Flat/Flat_15.0s_Bin1_5_20241123-053514_0006.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Flat/Flat_15.0s_Bin1_5_20241123-053532_0007.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Flat/Flat_15.0s_Bin1_5_20241123-053550_0008.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Flat/Flat_15.0s_Bin1_5_20241123-053608_0009.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Flat/Flat_15.0s_Bin1_5_20241123-053625_0010.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Flat/Flat_15.0s_Bin1_5_20241123-053731_0001.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Flat/Flat_15.0s_Bin1_5_20241123-053749_0002.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Flat/Flat_15.0s_Bin1_5_20241123-053807_0003.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Flat/Flat_15.0s_Bin1_5_20241123-053825_0004.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Flat/Flat_15.0s_Bin1_5_20241123-053843_0005.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Flat/Flat_15.0s_Bin1_5_20241123-053901_0006.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Flat/Flat_15.0s_Bin1_5_20241123-054039_0007.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Flat/Flat_15.0s_Bin1_5_20241123-054057_0008.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Flat/Flat_15.0s_Bin1_5_20241123-054115_0009.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/Flat/Flat_15.0s_Bin1_5_20241123-054132_0010.fit
  method: winsorized-mean
light_frames:
  files:
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241122-230155_0001.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241122-230658_0002.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241122-231201_0003.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241122-231704_0004.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241122-232207_0005.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241122-232717_0006.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241122-233220_0007.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241122-233723_0008.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241122-234225_0009.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241122-234728_0010.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241122-235236_0011.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241122-235739_0012.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-000747_0013.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-001250_0014.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-001753_0015.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-002301_0016.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-002804_0017.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-003307_0018.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-004403_0019.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-004905_0020.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-005413_0021.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-005915_0022.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-010418_0023.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-010921_0024.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-011424_0025.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-011931_0026.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-012434_0027.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-012937_0028.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-013439_0029.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-013942_0030.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-014449_0031.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-014952_0032.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-015455_0033.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-015958_0034.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-020501_0035.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-021008_0036.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-024734_0041.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-030840_0042.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-031343_0043.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-031846_0044.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-032349_0045.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-032859_0046.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-033402_0047.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-033905_0048.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-034408_0049.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-034910_0050.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-035418_0051.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-035921_0052.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-040424_0053.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-040927_0054.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-041430_0055.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-041938_0056.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-042441_0057.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-042944_0058.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-043447_0059.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-043950_0060.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-044459_0061.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-045002_0062.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-045505_0063.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-050008_0064.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-050511_0065.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-051019_0066.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-051522_0067.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-052025_0068.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-052528_0069.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_5_20241123-053031_0070.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_20241123-021511_0037.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_20241123-022014_0038.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_20241123-022517_0039.fit
  - /media/donut/Drive1/Temp_DSO_Stacker_Data/rosetta/Light_NGC2244SatelliteCluster_300.0s_Bin1_20241123-023020_0040.fit
  reference_index: 0
options:
  batch_size: 16
  bayer: auto
  bias_method: winsorized-mean
  bit_depth: f32
  dark_method: winsorized-mean
  darkflat_method: winsorized-mean
  flat_method: winsorized-mean
  integration: kappa-sigma
  iterations: 3
  kappa: 3.0
  match_device: auto
  match_radius: 30.0
  min_inliers: 10
  min_stars: 20
  moffat_alpha: 2.5
  moffat_beta: 2.0
  output_path: output.fits
  save_master_dir: ./master
  star_sigma: 3.0
  stretch_max: null
  stretch_min: null
  tiff_compression: none
  top_stars: 50
  triangle_iters: 1000
  triangle_thresh: 2.0
  use_cpu: false
  wsor_clip: 0.1
version: 1
